fix: no changing of mcid on cold app start
mparticle-integrations/mparticle-android-integration-adobe pull request #24
Opened 2022-12-06 00:33 UTC by mchuangatmp

## Summary
- Fix mcid changing on cold app start

## Testing Plan
- Regression tests should pass
- MCID stays same on cold app starts

## Reference Issue
- Closes https://go.mparticle.com/work/SQDSDKS-4935

2022-12-06 21:27 UTC, samdozor commented on src/main/kotlin/com/mparticle/kits/AdobeKitBase.kt
> -        marketingCloudId
if this is the type of stuff that kotlin autogen creates - we need to outlaw its use.

2022-12-06 22:14 UTC, mchuangatmp commented on src/main/kotlin/com/mparticle/kits/AdobeKitBase.kt
> -        marketingCloudId
original code was a `getMarketingCloudId()` in Java...in Adobe media kit change, we switched to `syncIds()` so i defaulted to align with that approach.

2022-12-07 13:36 UTC, samdozor commented on src/main/kotlin/com/mparticle/kits/AdobeKitBase.kt
> -        marketingCloudId
and yea syncIds() looks like the right approach. My overall concern is I think this is not the first bug that the autogen has introduced. I don't see it being worth it - or perhaps we need to change our approach to how we are doing this? 

perhaps - absolutely no autogen in the core SDK. the business impact of a bug there is too large.

2022-12-07 13:36 UTC, samdozor commented on src/main/kotlin/com/mparticle/kits/AdobeKitBase.kt
> -        marketingCloudId
cc @markvdouw who is thinking about this too

2022-12-07 13:50 UTC, markvdouw commented on src/main/kotlin/com/mparticle/kits/AdobeKitBase.kt
> -        marketingCloudId
I would say that the contracts and all main abstractions should be reviewed based on the business logic we want to achieve. I don't mind auto-converting utility functions as long as they don't are main pieces of the sdk itself. I would say that there is no point in, after converting the contract, also auto-converting the implementation at least on the core-sdk just "to say we are using kt".

In my opinion we will benefit not from the conversion of the implementations on its own, but from an organized overall rearchitecture, which will include not a 1:1 conversion from Java->Kt, but an overall architecture in Kt considering quality attributes, performance, alignment to best practices/design principles and scalability.
I strongly believe that migrating to Kt should not be a goal /milestone on its own, unless its not critical code; but part of adding value while rearchitecting/refactoring supported by audited interfaces and unit tests.

Sorry for the long text

2022-12-07 14:07 UTC, markvdouw requested changes

2022-12-07 14:07 UTC, markvdouw commented on src/main/kotlin/com/mparticle/kits/AdobeKitBase.kt
> +            if ((id?.length ?: 0 ) > 0 && !id.equals(integrationAttributes[MARKETING_CLOUD_ID_KEY])) {
!id.isNullOrEmpty() && ..

2022-12-07 18:07 UTC, mchuangatmp commented on src/main/kotlin/com/mparticle/kits/AdobeKitBase.kt
> +            if ((id?.length ?: 0 ) > 0 && !id.equals(integrationAttributes[MARKETING_CLOUD_ID_KEY])) {
good suggestion, fixed

2022-12-08 17:42 UTC, einsteinx2 approved these changes
LGTM

2022-12-08 17:47 UTC, merged